config/routes.rb
Rails.application.routes.draw do
  resources :debitos
  resources :contratos
  # ROTAS PRINCIPAIS
  root to: "home#index"
  
  # ROTAS DO SISTEMA
  resources :userconfs

  # ROTAS DO DEVISE
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
end

app/models/userconf.rb
class Userconf < ApplicationRecord
  belongs_to :user
  belongs_to :contrato, optional: true
  belongs_to :debito, optional: true
end

app/controllers/userconfs_controller.rb
class UserconfsController < ApplicationController
  before_action :set_userconf, only: %i[ show edit update destroy ]

  # GET /userconfs or /userconfs.json
  def index
    @userconfs = Userconf.all
  end

  # GET /userconfs/1 or /userconfs/1.json
  def show
  end

  # GET /userconfs/new
  def new
    @userconf = Userconf.new
  end

  # GET /userconfs/1/edit
  def edit
  end

  # POST /userconfs or /userconfs.json
  def create
    @userconf = Userconf.new(userconf_params)

    respond_to do |format|
      if @userconf.save
        format.html { redirect_to @userconf, notice: "Userconf was successfully created." }
        format.json { render :show, status: :created, location: @userconf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @userconf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userconfs/1 or /userconfs/1.json
  def update
    respond_to do |format|
      if @userconf.update(userconf_params)
        format.html { redirect_to @userconf, notice: "Userconf was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @userconf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userconf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userconfs/1 or /userconfs/1.json
  def destroy
    @userconf.destroy!

    respond_to do |format|
      format.html { redirect_to userconfs_path, notice: "Userconf was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userconf
      @userconf = Userconf.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def userconf_params
      params.fetch(:userconf, {})
    end
end

app/helpers/userconfs_helper.rb
module UserconfsHelper
end

app/views/userconfs/_form.html.erb
<%= form_with(model: userconf) do |form| %>
  <% if userconf.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(userconf.errors.count, "error") %> prohibited this userconf from being saved:</h2>

      <ul>
        <% userconf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/userconfs/_userconf.html.erb
<div id="<%= dom_id userconf %>">
</div>

app/views/userconfs/edit.html.erb
<% content_for :title, "Editing userconf" %>

<h1>Editing userconf</h1>

<%= render "form", userconf: @userconf %>

<br>

<div>
  <%= link_to "Show this userconf", @userconf %> |
  <%= link_to "Back to userconfs", userconfs_path %>
</div>

app/views/userconfs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Userconfs" %>

<h1>Userconfs</h1>

<div id="userconfs">
  <% @userconfs.each do |userconf| %>
    <%= render userconf %>
    <p>
      <%= link_to "Show this userconf", userconf %>
    </p>
  <% end %>
</div>

<%= link_to "New userconf", new_userconf_path %>

app/views/userconfs/new.html.erb
<% content_for :title, "New userconf" %>

<h1>New userconf</h1>

<%= render "form", userconf: @userconf %>

<br>

<div>
  <%= link_to "Back to userconfs", userconfs_path %>
</div>

app/views/userconfs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @userconf %>

<div>
  <%= link_to "Edit this userconf", edit_userconf_path(@userconf) %> |
  <%= link_to "Back to userconfs", userconfs_path %>

  <%= button_to "Destroy this userconf", @userconf, method: :delete %>
</div>