config/routes.rb
Rails.application.routes.draw do
  resources :debitos
  resources :contratos
  # ROTAS PRINCIPAIS
  root to: "home#index"
  
  # ROTAS DO SISTEMA
  resources :userconfs

  # ROTAS DO DEVISE
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
end

app/models/contrato.rb
class Contrato < ApplicationRecord
  has_one :userconf
  has_many :debito
  before_save :formata_salario
  before_save :gera_hora_extra
  validate :valida_campos

  def gera_hora_extra
    return unless horas_semanais.present? && salario_bruto.present? && horas_semanais > 0

    horas_mensais = horas_semanais * 4.33
    self.horas_mensais = horas_mensais

    hora_normal = salario_bruto / horas_mensais
    hora_extra = hora_normal * 1.5

    self.vlr_hr_normal = hora_normal
    self.vlr_hr_extra = hora_extra
  end

  def valida_campos
    # Valida vazios
    errors.add(:base, "Nome da empresa não foi informado!") if !self.nome_empresa.present?
    errors.add(:base, "Salário bruto não foi informado!") if !self.salario_bruto.present?
    errors.add(:base, "Horas semanais não foram informadas!") if !self.horas_semanais.present?

    # Valida formatos
    errors.add(:base, "Nome da empresa não é válido!") if self.nome_empresa.match?(/[*_|\/]/)
    errors.add(:base, "Formato de salário não aceito!") if self.salario_bruto.to_s.match?(/\A\d+\z/)

    # Valida valores inseridos
    errors.add(:base, "Salário não pode ser menor que R$ 0, 00 reais!") if self.salario_bruto <= 0
    errors.add(:base, "Horas semanais não pode ser menor ou igual a 0") if self.horas_semanais <= 0
  end

  def formata_salario
    self.salario_liquido = CalculosLegislacao.calcula_salario_liquido(self.salario_bruto)
  end
end

app/controllers/contratos_controller.rb
class ContratosController < ApplicationController
  before_action :set_contrato, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /contratos or /contratos.json
  def index
    @contratos = Contrato.all
  end

  # GET /contratos/1 or /contratos/1.json
  def show
  end

  # GET /contratos/new
  def new
    @contrato = Contrato.new
  end

  # GET /contratos/1/edit
  def edit
  end

  # POST /contratos or /contratos.json
  def create
    @contrato = Contrato.new(contrato_params)
    @contrato.userconf_id = current_user.userconf.id
    @contrato.salario_bruto = remove_formato_moeda(params[:contrato][:salario_bruto]) || 0

    respond_to do |format|
      if @contrato.save
        format.html { redirect_to @contrato, notice: "Contrato was successfully created." }
        format.json { render :show, status: :created, location: @contrato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contratos/1 or /contratos/1.json
  def update
    respond_to do |format|
      if @contrato.update(contrato_params)
        format.html { redirect_to @contrato, notice: "Contrato was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @contrato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contratos/1 or /contratos/1.json
  def destroy
    @contrato.destroy!

    respond_to do |format|
      format.html { redirect_to contratos_path, notice: "Contrato was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contrato
      @contrato = Contrato.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contrato_params
      params.require(:contrato).permit(:nome_empresa, :salario_bruto, :salario_liquido, :horas_semanais)
    end

    def remove_formato_moeda(valor)
      valor
        .gsub(/[^\d,]/, "")
        .gsub(",", ".")
        .to_f
    end
end

app/helpers/contratos_helper.rb
module ContratosHelper
end

app/views/contratos/_contrato.html.erb
<div id="<%= dom_id contrato %>">
</div>

app/views/contratos/_form.html.erb
<%= form_with(model: contrato) do |form| %>
  <% if contrato.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contrato.errors.count, "error") %> prohibited this contrato from being saved:</h2>

      <ul>
        <% contrato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nome da empresa :" %><br />
    <%= form.text_field :nome_empresa, placeholder: "Digite um nome", title: "Informe o nome da empresa que vai ser criado o contrato", required: true %>
  </div>

  <div class="field">
    <%= form.label "Salário bruto :" %><br />
    <%= form.text_field :salario_bruto, placeholder: "Digite um valor", title: "Informe o salário bruto por mensal", required: true, data: { moeda: true } %>
  </div>

  <div class="field">
    <%= form.label "Horas semanais trabalhadas" %><br />
    <%= form.number_field :horas_semanais, placeholder: "Digite um valor", title: "Informe suas horas semanais", required: true %>
  </div>

  <div>
    <%= form.submit "Criar contrato" %>
  </div>
<% end %>

app/views/contratos/edit.html.erb
<% content_for :title, "Editing contrato" %>

<h1>Editing contrato</h1>

<%= render "form", contrato: @contrato %>

<br>

<div>
  <%= link_to "Show this contrato", @contrato %> |
  <%= link_to "Back to contratos", contratos_path %>
</div>

app/views/contratos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contratos" %>

<h1>Contratos</h1>

<table>
    <thead>
      <tr>
        <th>Nome da Empresa</th>
        <th>Salário Bruto</th>
        <th>Salário Líquido</th>
        <th>Horas semanais</th>
      </tr>
    </thead>

    <tbody>

      <% @contratos.each do |c| %>
        <tr>
          <td><%= c.nome_empresa %></td>
          <td><%= c.salario_bruto %></td>
          <td><%= c.salario_liquido %></td>
          <td><%= c.horas_semanais %></td>
          <td><%= link_to "Visualizar", c %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<hr>

<br>

<%= link_to "Criar novo", new_contrato_path %>
<%= link_to "Voltar", root_path %>

app/views/contratos/new.html.erb
<% content_for :title, "New contrato" %>

<h1>Criar Contrato</h1>

<%= render "form", contrato: @contrato %>

<br>

<div>
  <%= link_to "Voltar para Contratos", contratos_path %>
</div>

app/views/contratos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contrato %>

<div>
  <%= link_to "Edit this contrato", edit_contrato_path(@contrato) %> |
  <%= link_to "Back to contratos", contratos_path %>

  <%= button_to "Destroy this contrato", @contrato, method: :delete %>
</div>