config/routes.rb
Rails.application.routes.draw do
  resources :debitos
  resources :contratos
  # ROTAS PRINCIPAIS
  root to: "home#index"
  
  # ROTAS DO SISTEMA
  resources :userconfs

  # ROTAS DO DEVISE
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
end

app/views/layouts/_sidebar.html.erb
<!-- MENU LATERAL -->
<span class="menu-toggle">☰</span>
<div class="sidebar">
<p class="text-center text-white fs-5 fw-bolder">Seja bem vindo, <%= "#{current_user.userconf.nome}"%>!</p>

<%= link_to "🏠 Home #{current_page?(root_path) ? '👈' : ''}", root_path %>
<%= link_to "💲 Débitos #{current_page?(debitos_path) ? '👈' : ''}", debitos_path %>
<%= link_to "📝 Contratos #{current_page?(contratos_path) ? '👈' : ''}", contratos_path %>
<a href="#">⚙️ Configurações</a>
<%= button_to destroy_user_session_path,
    method: :delete,
    class: "logout-link",
    form: { class: "logout-form" } do %>
    🚪 Sair
<% end %>
</div>

<script>
    const toggle = document.querySelector('.menu-toggle');
    const sidebar = document.querySelector('.sidebar');
    const content = document.querySelector('.content');

    toggle.addEventListener('click', () => {
        sidebar.classList.toggle('active');
        content.classList.toggle('shift');
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Contasorg" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Contasorg">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- CSS do template -->
    <%= stylesheet_link_tag "fontawesome/all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "sb-admin-2.min", "data-turbo-track": "reload" %>

    <!-- CSS da aplicação -->
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <%# Importmap %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>